<Project Sdk="Dalamud.NET.Sdk/12.0.0">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <DalamudApiLevel>12</DalamudApiLevel>

    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <Version>0.0.0.1</Version>
    <PackageProjectUrl>https://github.com/goatcorp/autoLeve</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\Data\goat.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
  </ItemGroup>
</Project>